### ISSUE TITLE
bare6-9 feedback

### ISSUE THREAD

**Issue by Decending** [Partins/e7020e_2021_marbla#4]
_**General feedback**_

By removing the indications for where your answers are to be makes it a lot harder to find them at a glance, keep the 
** Your answer here ** flags to make it easier for us reviewers.

-----------------------------------

_**Bare6**_

Looks good, your conclusions regarding the prescaler is correct throughout.

-----------------------------------

_**Bare7**_

Looks good, your generalization seems correct.

-----------------------------------

_**Bare8**_

You seem to get a similar results to most. I think your conclusions are correct.
What would be the maximum amount of letters your program could theoretically take in? Could be worth looking into for the project.

-----------------------------------

_**Bare9**_

This solution will work, but there are certain optimizations you can make.
For example, do we really need to know the amount of sucessful transfers? We're really only interested in the lost ones, right? Given that we've confirmed that we always receive up to 16 letters without fault.

Another thing you could think about implementing is moving the prints to a lower prioritized task, such as priority 0, as the prints are the least important part for the functionallity of the program.

**Comment by Partins** [comment]
Thank you for the comments
